- project:
    templates:
      - openstack-lower-constraints-jobs
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
    check:
      jobs:
        - openstack-tox-docs
    gate:
      jobs:
        - openstack-tox-docs

