#!/bin/bash

set -eux
set -o pipefail

if [[ ${DISTRO_NAME} =~ "centos" ]]; then
     yum install -y epel-release
     yum install -y gcc
     yum update -y
else
    if [[ ${DISTRO_NAME} =~ "ubuntu" ]]; then
        apt-get install -y build-essential
    fi
fi


