heat_template_version: 2013-05-23

description: >
  HOT template to create a new neutron network plus a router to the public
  network, and for deploying servers into the new network.

parameters:
  external_net:
    type: string
    description: ID or name of public network for which floating IP addresses will be allocated
  flavor:
    type: string
    description: Flavor to use for servers
  dns_nameservers:
    type: comma_delimited_list
    description: DNS nameservers for the image builder subnet

resources:
  private_net:
    type: OS::Neutron::Net
    properties:
      name: shaker_image_builder_net

  private_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: private_net }
      cidr: 10.0.0.0/29
      dns_nameservers: { get_param: dns_nameservers }

  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: { get_param: external_net }

  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router }
      subnet_id: { get_resource: private_subnet }

  master_image:
    type: OS::Glance::Image
    properties:
      container_format: bare
      disk_format: qcow2
      location: http://cdimage.debian.org/cdimage/openstack/8.1.0/debian-8.1.0-openstack-amd64.qcow2
      min_disk: 3
      min_ram: 512
      name: shaker_image_build_template

  master_image_server_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: private_net }
      fixed_ips:
        - subnet_id: { get_resource: private_subnet }

  master_image_server:
    type: OS::Nova::Server
    properties:
      name: shaker_image_builder_server
      image: { get_resource: master_image }
      flavor: { get_param: flavor }
      networks:
        - port: { get_resource: master_image_server_port }
      user_data_format: RAW
      user_data: |
        #!/bin/bash
        sudo apt-add-repository "deb http://nova.clouds.archive.ubuntu.com/ubuntu/ trusty multiverse"
        sudo apt-get update
        sudo apt-get -y install iperf netperf python-dev libzmq-dev screen
        wget -O get-pip.py https://bootstrap.pypa.io/get-pip.py && sudo python get-pip.py
        sudo pip install flent pyshaker-agent
        echo -e 'start on startup\ntask\nexec /usr/bin/screen -dmS sudo nice -n -20 /usr/bin/iperf -s' | sudo tee /etc/init/iperf-tcp.conf
        echo -e 'start on startup\ntask\nexec /usr/bin/screen -dmS sudo nice -n -20 /usr/bin/iperf -s --udp' | sudo tee /etc/init/iperf-udp.conf
        sudo shutdown now

outputs:
  server_info:
    value: { get_attr: [ master_image_server, show ] }
